@startuml ViewProducts

' === Style Tweaks ===

skinparam {
  Style StrictUML
  RoundCorner 5
  ParticipantPadding 10
  Padding 2
  SequenceStereotype {
    Font {
      Size 11
      Style plain
    }
  }
  Database {
    BorderColor #A80036
  }
}

' === Actors / Participants

actor "Customer" as user
participant "view-products" as viewPage << JSP Page >>
participant "ProductDAO / ProductJdbiDAO" as dao << DAO >>
database "Database H2" as db

' === Interactions ===



user -> viewPage : Clicks "view product" button


viewPage -> dao++ : GET request
viewPage -> dao : getParameter("category")

dao -> db++ : select distinct category from Product order by category ASC
return collection of categories
dao --> viewPage: collection of categories
viewPage -> dao : getProducts()
dao -> db : select * from Product order by productId
db --> dao: return collection of products  
return collection of products


viewPage->viewPage : display products



@enduml
