/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  yukiyoshiyasu
 * Created: 18/08/2023
 */

create table if not exists Product (
    productId INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    category VARCHAR(255),
    listPrice NUMERIC(10, 2),
    quantityInStock NUMERIC(10, 2),
    CONSTRAINT chk_id_positive CHECK (productId > 0),
    CONSTRAINT chk_name_length CHECK (LENGTH(name) >= 2)
);

CREATE TABLE IF NOT EXISTS Customer (
    customerId INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1000) PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    firstName VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    shippingAddress VARCHAR(255),
    emailAddress VARCHAR(255),
    password VARCHAR(255) NOT NULL
);

